name: Move a major tag to the latest release

on:
  push:
    tags:
      - v**

jobs:
  tag:
    name: Move major tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Move major tag
        uses: ./
